---
title: "figures"
author: "Austin Kennedy"
date: '2022-04-16'
output: html_document
---


```{r Clear memory and setup}
rm(list=ls())
options(scipen=999)
```


```{r Load Packages}
library(tidyverse)
library(vroom)
library(lubridate)
```

```{r Load Matched Trades Data}
trades_matched <- vroom('../temporary/matched_trades.csv')
trades_matched$date <- as.POSIXct(trades_matched$date, format = "%Y-%m-%d %H:%M:%S", tz = "UTC")
```

```{r Load Transaction Data}
trades <- vroom('../temporary/trades_cleaned.csv')
trades$date <- as.POSIXct(trades$date, format = "%Y-%m-%d %H:%M:%S", tz = "UTC")
```


```{r Functions}
#unit should be in the form of "amount" (for BTC), "amount_nominal" (domestic currency), or "amount_usd"
get_volume <- function(data, unit, window){
  df <- data %>%
    group_by(time = as.Date(floor_date(date, window))) %>%
    summarise(volume = sum({{unit}}))
  
  return(df)
}

get_volume_price <- function(data, unit, window){
  df <- data %>%
    group_by(time = as.Date(floor_date(date, window))) %>%
    summarise(volume = sum({{unit}}), price = mean(Close))
  
  return(df)
}

# agg_outflow <- function(data, country){
#   outflows <- data %>%
#     filter((Currency == toString(country)) & (Currency2 != toString(country)))
#   
#   p <- ggplot(outflows)
# }

```



```{r Russia-Ukraine}
agg <- trades_matched %>%
  filter((Currency == "RUB"))  %>%
  group_by(daily = as.Date(date)) %>%
  summarise(volume = sum(amount_usd))

vline <- which(agg$daily %in% as.Date(c("2022-02-24")))

ggplot(agg, aes(x=daily, y=volume)) +
  geom_line(color = "blue", siize = 0.8) +
  geom_vline(xintercept = as.numeric(agg$daily[vline]), color='red') +
  xlab("2022") +
  ylab("USD") +
  ylim(0,40000) +
  scale_x_date(limit=c(as.Date("2022-02-01"), as.Date("2022-09-01"))) +
  ggtitle('RUB Volume (Daily)(Matched Trades)') +
  theme_bw() +
  theme(plot.title = element_text(size = 15, hjust = 0.5))

ggsave('../output/figures/russia_vehicle.png')
```

```{r Top Exporting}
top_export <- trades_matched %>%
  filter(Currency != Currency2) %>%
  group_by(Currency) %>%
  summarise(total = sum(amount_usd)) %>%
  arrange(desc(total)) %>%
  slice(1:5)

exporters <- top_export$Currency


agg_exporters <- trades_matched %>%
  filter((Currency %in% exporters) & (Currency != Currency2)) %>%
  group_by(Currency, time = as.Date(floor_date(date, "month"))) %>%
  summarise(volume = sum(amount_usd))

ggplot(agg_exporters, aes(x=time, y=volume, color = Currency)) +
  geom_line(size=0.8) +
  xlab("") +
  # ylim(0,300) +
  theme_bw() +
  ggtitle("Top Exporters")

  # scale_x_date(limit=c(as.Date("2017-01-01"), as.Date("2022-01-01")))

# ggsave("../output/exporters_full.png")

```

```{r importers}
top_import <- trades_matched %>%
  filter(Currency != Currency2) %>%
  group_by(Currency2) %>%
  summarise(total = sum(amount_usd)) %>%
  arrange(desc(total)) %>%
  slice(1:5)

importers <- top_import$Currency2

library(lubridate)

agg_importers <- trades_matched %>%
  filter((Currency2 %in% importers) & (Currency != Currency2)) %>%
  group_by(Currency2, time = as.Date(floor_date(date, "month"))) %>%
  summarise(volume = sum(amount_usd))

ggplot(agg_importers, aes(x=time, y=volume, color = Currency2)) +
  geom_line(size = 0.8) +
  xlab("") +
  # ylim(0,300) +
  theme_bw() +
  ggtitle("Top Importers") #+
  # scale_x_date(limit=c(as.Date("2020-01-01"), as.Date("2022-01-01")))

# ggsave("../output/importers_full.png")

```

```{r LocalBitcoins Volume}
trade_volume <- get_volume(trades, amount_usd, 'week')

trade_volume_price <- get_volume_price(trades, amount_usd, 'week')

ggplot(trade_volume_price, aes(x=time)) +
  geom_line(aes(y = volume), color = "blue", size=0.6) +
  geom_line(aes(y = price*1200), color = "black", size=0.6) +
  xlab("") +
  ylab("USD") +
  theme_bw() +
  ggtitle("LocalBitcoins Volume (Weekly)") +
  scale_y_continuous(breaks = c(50000000, 100000000), labels = c("$50M", "$100M"),
                     sec.axis = sec_axis(trans = ~./1200, name = "Price")) +
  theme(plot.title = element_text(size = 15, hjust = 0.5))

ggsave('../output/figures/localbtc_volume_price.png')

# ggplot(trade_volume_price, aes(x=time)) +
#   geom_line(aes(y = volume), color = "blue", size=0.8) +
#   xlab("") +  
#   ylab("USD") +
#   theme_bw() +
#   ggtitle("LocalBitcoins Volume (Weekly)") +
#   scale_y_continuous(breaks = c(50000000, 100000000), labels = c("$50M", "$100M")) +
#   theme(plot.title = element_text(size = 20, hjust = 0.5))
# 
# ggsave('../output/figures/localbtc_volume.png')
```


```{r Summary Stats}

avg_usd <- mean(trades$amount_usd)

max_usd <- max(trades$amount_usd)

total_volume <- sum(trades$amount_usd)
```

```{r Cross-Border}
top_partners <- trades_matched %>%
  filter(Currency != Currency2) %>%
  group_by(Currency, Currency2) %>%
  summarise(trade = sum(amount_usd))

top_partners <- top_partners %>%
  arrange(desc(trade))
```











